### ISSUE TITLE
Handle static requests outside of the browser's page

### ISSUE THREAD

**Issue by gahabeen** [apify/apify-ts#79]
**Describe the feature**
While using a BrowserCrawler (Playwright or Puppeteer for ex), run the static requests outside of the browser (via a fetch or got-scraping) instead of using a page (by overriding its settings).

**Motivation**
Within a single actor I want to run static requests while still benefitting from some features like:
- the scaling (concurrency against available resources)
- the general proxy settings
- the retries settings
- the requests states (for general tracking & resurrections capabilities)

I don't like doing requests within the **requestHandleFunction**  while we already have a requestQueue that should be here to handle these (with many benefits).

**Constraints**
It needs to use all settings passed to the browser (session, proxy, cookies, etc).

**Proof of Concept**
Available here, I've made a quick patch that does what I described above. Also it doesn't handle some aspects (like sessions) for now, let's say it does the trick.

**Comment by barjin** [comment]
Hello, going back to this for the second time, as it is still open :)
If I understand correctly, the goal is to have some mechanism for marking requests as "static," i.e. can be fetched and processed without an actual browser (static web pages, images, stylesheets...?)

I can't seem to have access to any of the repositories posted above. What is the intended usage?
Right now, the `RequestQueue` instance is passed directly to the (Playwright|Puppeteer|...)Crawler, along with the `handlePageFunction`. 

If we are making this dichotomy (browser/static request), I guess there must be a difference in the request handling logic. 
How (and where) do we pass the `staticHandlePageFunction`, i.e. the logic for handling the "static" requests?

**Comment by metalwarrior665** [comment]
Let's not use the word "static", I don't think it makes much sense in what we want to do. I would call it `no-browser` or `http-only`.

I think the simplest way would be to pass it in the `request` object or maybe have some hook where you can route them either to browser or plain HTTP. But of course, there are more options :)

**Comment by gahabeen** [comment]
@barjin Indeed, I think your idea of a `httpHandlePageFunction` is great but then there should be a `mode` key on the Request to know how it should be processed (`browser` or `http`).

The actual real solution to this would not be doing this but instead be able to have this `mode` and use the same `RequestQueue` on several Crawlers 😎

**Comment by B4nan** [comment]
> I would call it no-browser or http-only or plain-http.

I like `httpOnly: true` (its an object property, so should be camel cased).

>  but then there should be a mode key on the Request to know how it should be processed (browser or http).

Why another option? You would already have the `Request.httpOnly` exactly for this, to distinguish from regular browser requests.

**Comment by metalwarrior665** [comment]
The "more crawlers" use-case is not necessary I think for most problem. Usually, you just need to combine browser & non-browser in one crawler so you don't have to use `fetch`

**Comment by metalwarrior665** [comment]
The design decision is if we want to have a separate handlePage function for it or use the normal one (but pollute its types because there will be no `page`)

**Comment by mnmkng** [comment]
Guys, I'd like to get back to my earlier comment. 

> I think we should support some intuitive way of solving this problem. It does not necessarily have to be "multiple ways of handling requests in a crawler", but maybe just a way to skip navigation and go directly to handle page function, or something like that.

The point is, I don't think we need to figure out what kind of use-cases the user potentially wants to solve with this. http only, static, whatever. The only thing we need to do is to give them a chance to process the request on their own. This they can already do with the current `handlePageFunction` (with a route), so we don't need a new handler for that. The only thing we need to do is to enable users to skip navigation, because that's the part of the request lifecycle the users can't control.

**Comment by B4nan** [comment]
I guess you are right, let's do it that way. FYI we will also have a helper method directly in the context to be able to process our `Request` objects directly via got-scraping (kind of like the `requestAsBrowser`, but contextual, so will respect proxy configuration). https://github.com/apify/apify-ts/issues/74

**Comment by metalwarrior665** [comment]
That's a great resolution, much better :)

**Comment by mnmkng** [comment]
Just be careful that `Request.skipNavigation` will not persist to RequestQueue unless you tell platform guys to change the Request schema on API.

You'd have to do `request.userData.skipNavigation` to persist it. But that clashes with potential user data.

So, přílepek incoming, let's save it under `request.userData.__apify.skipNavigation`. The `__apify` object should be automatically parsed into `Request` properties and removed from `userData` when the `request` is pulled from the queue. The user will never see it unless they pull from API manually.

I was thinking about having some kind of private metadata object like this for some time, because it would allow us to store more information with the request.

What do you think?

**Comment by B4nan** [comment]
> So, přílepek incoming, let's save it under request.userData.__apify.skipNavigation. The __apify object should be automatically parsed into Request properties and removed from userData when the request is pulled from the queue. The user will never see it unless they pull from API manually.

That's some dark magic that already works or are you suggesting us to implement it now? Because the library is no longer called "apify", so unless this would be some hack in the apify-client, I don't like the name `__apify` :]

For users we definitely need `Request.skipNavigation` (or something directly on the object, without any `__` prefixes or additional nesting under `userData`. I don't mind if it will be a get/set pair instead of actual property.

**Comment by mnmkng** [comment]
> For users we definitely need Request.skipNavigation

Let me clarify:

```js
// somewhere in user code
request.skipNavigation()

// in Request class
skipNavigation() {
    this.privateProps.skipNavigation = true;
}

// when serializing for API
request.userData = this.userData
request.userData.__apify|crawlee = this.privateProps

// when deserializing
this.privateProps = request.userData.__apify|crawlee
delete request.userData.__apify|crawlee
this.userData = request.userData
```

**Comment by B4nan** [comment]
Ok got it, lets use get/set property instead of a method, and `__crawlee` as the key (or maybe even something like `__internal`).

**Comment by mnmkng** [comment]
I would use __crawlee, because anybody could use __internal.
